[package]
name = "dht"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
actix = "0.12"
actix-rt = "2.5"
log = "0.4"
pretty_env_logger = "0.4"